### PR TITLE
feat(bar): impl Styled for Bar

### PR DESCRIPTION
**Pull request by Emivvvvv**
implements `styled` for `Bar`: https://github.com/ratatui/ratatui/issues/683

### CODE REVIEW

**Review by orhun — APPROVED** [review]
LGTM!

**Review by joshka — APPROVED** [review]

**Comment by orhun** [comment]
We will come back to this after #1388 is complete.

**Comment by joshka** [comment]
rebased on main and fixed up

**Comment by joshka** [comment]
Thanks for your work on this @Emivvvvv

**Pull request merged**
